issue#7: added '-p' and '-s' options for manage luks password; improved script's output

diff --git a/makefreepto b/makefreepto
--- a/makefreepto
+++ b/makefreepto
@@ -9,21 +9,31 @@ Options:
     -r         skip random filling (use only if you know what you are doing)
     -w         skip dd of binary.img
     -i IMAGE   put IMAGE on DEVICE (default is binary.img)
+    -p         set password (defaul is "freepto")
+    -s         set secure random password (default is "freepto")
 EOF
 }
 
-# Check if user is root
+# set color:
+export LRED="\e[1;31m"
+export LGREEN="\e[1;32m"                                                                                                                                               
+export Z="\e[0m"
+
+# check if user is root:
 if [ "$(id -u)" != "0" ]; then
-   echo "[-] This script must be run as root" 1>&2
+   echo -e "$LRED[-] Only root can do that! $Z" 1>&2
    exit 1
 fi
 
+# set default:
 skip_badblocks=0
 skip_random=0
 skip_img=0
+password="freepto"
 img=binary.img
+log="./makefreepto.log"
 
-while getopts 'brwi:' opt; do
+while getopts 'brp:wsi:' opt; do
     case $opt in
     b)
         skip_badblocks=1
@@ -37,8 +47,15 @@ while getopts 'brwi:' opt; do
     w)
         skip_img=1
         ;;
+    p)
+        password=$OPTARG
+        ;;
+    s)
+        password=`tr -dc 'a-zA-H0-9' < /dev/urandom | head -c 12`
+        echo -e "$LGREEN[+]$Z Your LUKS random passphrase is: $LRED$password$Z"
+        ;;
     \?)
-        echo "[-] Invalid option: -$OPTARG" >&2
+        echo -e "$LRED[-] Invalid option: -$OPTARG $Z" >&2
         usage
         exit 1
         ;;
@@ -46,58 +63,61 @@ while getopts 'brwi:' opt; do
 done
 shift $((OPTIND-1))
 
+# some control check
 if ! [[ -f "$img" ]]; then
-    echo "[-] Image $img is not valid"
+    echo -e "$LRED[-] Image $img not exist or is not valid $Z"
     exit 1
 fi
 
 if [ $# != 1 ];then
-    echo "[-] Wrong argument number"
+    echo -e "$LRED[-] Wrong argument number $Z"
     usage
     exit 1
 fi
 
 if ! [[ -b $1 ]]; then
-    echo "[-] $1 should be a block special device"
+    echo -e "$LRED[-]$1 should be a block special device $Z"
     usage
     exit 1
 fi
+
+# set device
 device=$1
 
 # check dependencies
 if ! which mkfs.btrfs &> /dev/null; then
-     echo "[-] No btrfs. Setting up btrfs-tools"
-     sudo apt-get --force-yes --yes install btrfs-tools && echo "[+] Btrfs-tools installed!"
+     echo -e "$LRED[-] No btrfs. Setting up btrfs-tools $Z"
+     sudo apt-get --force-yes --yes install btrfs-tools >> $log 2>&1
+     echo -e "$LGREEN[+] $Z btrfs-tools package installed!"
 fi
 if ! which cryptsetup &> /dev/null; then
-     echo "[-] No cryptsetup. Setting up cryptsetup"
-     sudo apt-get --force-yes --yes install cryptsetup && echo "[+] Cryptsetup installed!"
+     echo -e "$LRED[-] No cryptsetup. Setting up cryptsetup $Z"
+     sudo apt-get --force-yes --yes install cryptsetup >> $log 2>&1
+     echo -e "$LGREEN[+]$Z cryptsetup pakcage installed!"
 fi
 
-# Start
-echo "[+] Start"
+# umount device and clean all partition:
+echo -e "$LGREEN[+]$Z Umount device ${device}"
+umount ${device} > $log 2>&1
+echo -e "$LGREEN[+]$Z Remove all partition on ${device}"
+mkfs.ext4 -F ${device} > $log 2>&1
 
-
-# Umount and clean all partition on the device:
-umount ${device}
-mkfs.ext4 -F ${device}
-
-
-# Check for bad block on the device:
+# check for bad block on the device:
 if [[ $skip_badblocks -eq 0 ]]; then
-    badblocks -c 10240 -s -w -t random -v "${device}"
-    echo "[+] Badblock check completed!"
+    echo -e "$LGREEN[+]$Z Badblock check started..."
+    badblocks -c 10240 -s -w -t random -v "${device}" >> $log 2>&1
+    echo -e "$LGREEN[+]$Z Badblock check completed!"
 fi
 
-# Random data on the device:
+# write random data on the device:
 if [[ $skip_random -eq 0 ]]; then
-    echo "[+] Writing random data on the device!"
-    dd if=/dev/urandom of="${device}"
-    echo "[+] Completed!"
+    echo -e "$LGREEN[+]$Z Writing random data on the device!"
+    dd if=/dev/urandom of="${device}" >> $log 2>&1
+    echo -e "$LGREEN[+]$Z Random writing completed!"
 fi
 
-# DD the .img to a usb
-echo -n "[+] Starting copy"
+# copy binay image with dd:
+echo -e "$LGREEN[+]$Z Starting copy"
 if [[ $skip_img -eq 0 ]]; then
 	dd "if=$img" of="${device}" &
 	ddpid=$!
@@ -110,46 +130,48 @@ if [[ $skip_img -eq 0 ]]; then
 	    sleep 10
 	done
 	wait
-	echo "[+] Completed!"
+	echo -e "$LGREEN[+]$Z Completed!"
 fi
 
-
-# Make the partition
-echo "[+] Make ecnrypted and persistent partition"
+# make the partition:
+echo -e "$LGREEN[+]$Z Make encrypted persistent partition"
 img_bytes=$(stat -c %s "$img")
 img_bytes=$((img_bytes+1))
 
 if [ -e "${device}"2 ]; then
-	echo "[W] warning: ${device}2 seems to already exist!"
+	echo -e "$LRED[-]$Z warning: ${device}2 seems to already exist!"
 fi
-partprobe
+partprobe 
 parted "${device}" -- mkpart primary "${img_bytes}B" -1
 partprobe #it was fun, let's do it again
 
-# Ecnrypt partition
-cryptsetup --verbose --batch-mode --key-size 512 --hash sha512 --cipher aes-xts-plain --use-random luksFormat "${device}2" <<<freepto || exit 1
+# encrypt partition
+cryptsetup --verbose --batch-mode --key-size 512 --hash sha512 --cipher aes-xts-plain --use-random luksFormat "${device}2" <<<${password} || exit 1
 
-# Open partition
-cryptsetup luksOpen "${device}2" my_usb.$$ <<<freepto || exit 1
+# open LUKS
+cryptsetup luksOpen "${device}2" my_usb.$$ <<<${password} || exit 1
 
-# Make FS with label: "persistence"
-mkfs.btrfs -L persistence /dev/mapper/my_usb.$$ || exit 1
+# make FS with label: "persistence"
+mkfs.btrfs -L persistence /dev/mapper/my_usb.$$ >> $log 2>&1 || exit 1
 
-# Make a mount point
-mkdir -p /mnt/my_usb.$$
+# make a mount point
+mkdir -p /mnt/freepto.$$
 
-# Munt the partition
-mount /dev/mapper/my_usb.$$ /mnt/my_usb.$$/ -o noatime,nodiratime,compress=lzo
+# mount the partition
+sleep 2
+mount /dev/mapper/my_usb.$$ /mnt/freepto.$$/ -o noatime,nodiratime,compress=lzo
 
-# Make the persistence.conf file
+# make the persistence.conf file
+sleep 2
 echo "/ union" > ~/persistence.conf
-mv ~/persistence.conf /mnt/my_usb.$$
+mv ~/persistence.conf /mnt/freepto.$$
 
-# Umount
-umount /dev/mapper/my_usb.$$
+# umount partition and close LUKS
+umount /mnt/freepto.$$ >> $log 2>&1 && cryptsetup luksClose /dev/mapper/my_usb.$$ >> $log 2>&1
 
-# Close LUKS
-cryptsetup luksClose /dev/mapper/my_usb.$$
+# remove mount dir
+rm -rf /mnt/freepto.$$ >> $log 2>&1
 
-# Remove mount dir
-rm -rf /mnt/my_usb.$$
+#start
+echo -e "$LGREEN[+]$Z Freepto è prota per l'uso"
+
