find all generated .deb files

diff --git a/auto/build b/auto/build
--- a/auto/build
+++ b/auto/build
@@ -62,14 +62,13 @@ _build_packages() {
 	mkdir -p config/packages.chroot/
 	find -L pkgs -maxdepth 1 -mindepth 1 -type d | \
 		while read pkg; do
-			_build_package "$pkg" || exit 1
-			deb=$(find "$pkg" -maxdepth 1 -type f -name '*.deb' -print0 |xargs -r0 ls -t1|head -n1)
-			if [ -z "$deb" ]; then
-				echo "deb generation failed for $pkg"
-				continue
+			_build_package "$pkg"
+			if [[ "$?" -ne 0 ]]; then
+				echo "ERROR: build for package $pkg failed"
 			fi
-			mv -f "$deb" "config/packages.chroot/"
 		done
+	find -L pkgs -maxdepth 2 -type f -name '*.deb' \
+		-exec mv -f {} "config/packages.chroot/" \;
 }
 
 _build_package() {
